env:
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - airbnb-base
  - prettier

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
